---
title: "Data Maniputation"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```


Let's import the `FAS_litters.csv` csv. in relative path.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)
```


## `select` 
used to select columns
```{r}
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, gd0_weight, group)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

select(litters_df, -litter_number)

select(litters_df, -starts_with("gd"))

select(litters_df, group, litter_id = litter_number)

select(litters_df, group, litter_id = litter_number, everything())

select(litters_df, gd0_weight, everything())

```

```{r}
rename(litters_df, litter_id = litter_number)

relocate(litters_df, litter_number)
```
give same result.

note: after rename the new name is not overwrite to the dataset becasue no saving as a new object but just select.

`select` vs `pull`
```{r}
select(litters_df, group)
pull(litters_df, group)
```

## la1
```{r}
select(pups_df, litter_number, sex, pd_ears)
```


##`filter`
```{r}
filter(litters_df, group == "Con7")

filter(litters_df, group != "Con7")

filter(litters_df, gd0_weight <= 20)

filter(litters_df, group == "Con7" | group == "Con8")

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con8"), gd0_weight > 20)
```


## `mutate`
this is used to add and change variables
```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, group = str_to_lower(group))
```

## drop missing value
```{r}
drop_na(litters_df, gd0_weight)

drop_na(litters_df)
```

## `arrange`
```{r}
arrange(litters_df, group, gd0_weight)
```

##pipes
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |>
  janitor::clean_names() |>
  select(-starts_with("pups")) |>
  mutate(
    group = str_to_lower(group),
    wt_gain = gd18_weight - gd0_weight,
  ) |>
  drop_na(wt_gain) |>
  arrange(group, wt_gain)
```







